# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(539, 350)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lab_node = QtWidgets.QLabel(self.centralwidget)
        self.lab_node.setGeometry(QtCore.QRect(20, 60, 54, 20))
        self.lab_node.setObjectName("lab_node")
        self.com_fault_node = QtWidgets.QComboBox(self.centralwidget)
        self.com_fault_node.setGeometry(QtCore.QRect(78, 58, 71, 22))
        self.com_fault_node.setObjectName("com_fault_node")
        self.btn_import_data = QtWidgets.QPushButton(self.centralwidget)
        self.btn_import_data.setGeometry(QtCore.QRect(20, 10, 75, 23))
        self.btn_import_data.setObjectName("btn_import_data")
        self.lab_type = QtWidgets.QLabel(self.centralwidget)
        self.lab_type.setGeometry(QtCore.QRect(20, 88, 54, 21))
        self.lab_type.setObjectName("lab_type")
        self.com_fault_type = QtWidgets.QComboBox(self.centralwidget)
        self.com_fault_type.setGeometry(QtCore.QRect(80, 88, 69, 22))
        self.com_fault_type.setObjectName("com_fault_type")
        self.lab_data = QtWidgets.QLabel(self.centralwidget)
        self.lab_data.setGeometry(QtCore.QRect(100, 12, 61, 20))
        self.lab_data.setObjectName("lab_data")
        self.line_step = QtWidgets.QLineEdit(self.centralwidget)
        self.line_step.setGeometry(QtCore.QRect(90, 170, 61, 20))
        self.line_step.setObjectName("line_step")
        self.com_var = QtWidgets.QComboBox(self.centralwidget)
        self.com_var.setGeometry(QtCore.QRect(240, 20, 69, 22))
        self.com_var.setObjectName("com_var")
        self.lab_var = QtWidgets.QLabel(self.centralwidget)
        self.lab_var.setGeometry(QtCore.QRect(180, 20, 54, 20))
        self.lab_var.setObjectName("lab_var")
        self.lab_step = QtWidgets.QLabel(self.centralwidget)
        self.lab_step.setGeometry(QtCore.QRect(20, 170, 61, 21))
        self.lab_step.setObjectName("lab_step")
        self.lab_cut_time = QtWidgets.QLabel(self.centralwidget)
        self.lab_cut_time.setGeometry(QtCore.QRect(0, 200, 91, 21))
        self.lab_cut_time.setObjectName("lab_cut_time")
        self.line_cut_time = QtWidgets.QLineEdit(self.centralwidget)
        self.line_cut_time.setGeometry(QtCore.QRect(90, 200, 61, 20))
        self.line_cut_time.setObjectName("line_cut_time")
        self.lab_total_time = QtWidgets.QLabel(self.centralwidget)
        self.lab_total_time.setGeometry(QtCore.QRect(10, 230, 81, 16))
        self.lab_total_time.setObjectName("lab_total_time")
        self.line_total_time = QtWidgets.QLineEdit(self.centralwidget)
        self.line_total_time.setGeometry(QtCore.QRect(90, 230, 61, 20))
        self.line_total_time.setObjectName("line_total_time")
        self.btn_start_simu = QtWidgets.QPushButton(self.centralwidget)
        self.btn_start_simu.setGeometry(QtCore.QRect(10, 260, 141, 71))
        self.btn_start_simu.setObjectName("btn_start_simu")
        self.lab_cut_branch = QtWidgets.QLabel(self.centralwidget)
        self.lab_cut_branch.setGeometry(QtCore.QRect(20, 108, 51, 41))
        self.lab_cut_branch.setWordWrap(True)
        self.lab_cut_branch.setObjectName("lab_cut_branch")
        self.com_cut_branch = QtWidgets.QComboBox(self.centralwidget)
        self.com_cut_branch.setGeometry(QtCore.QRect(80, 118, 69, 22))
        self.com_cut_branch.setObjectName("com_cut_branch")
        self.widget_pic = QtWidgets.QWidget(self.centralwidget)
        self.widget_pic.setGeometry(QtCore.QRect(170, 50, 351, 281))
        self.widget_pic.setObjectName("widget_pic")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 150, 101, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(50, 40, 71, 16))
        self.label_2.setObjectName("label_2")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lab_node.setText(_translate("MainWindow", "故障节点"))
        self.btn_import_data.setText(_translate("MainWindow", "导入数据"))
        self.lab_type.setText(_translate("MainWindow", "故障类型"))
        self.lab_data.setText(_translate("MainWindow", "数据名称"))
        self.line_step.setText(_translate("MainWindow", "0.01"))
        self.lab_var.setText(_translate("MainWindow", "查看变量"))
        self.lab_step.setText(_translate("MainWindow", "仿真步长/s"))
        self.lab_cut_time.setText(_translate("MainWindow", "故障切除时间/s"))
        self.line_cut_time.setText(_translate("MainWindow", "1"))
        self.lab_total_time.setText(_translate("MainWindow", "仿真总时长/s"))
        self.line_total_time.setText(_translate("MainWindow", "10"))
        self.btn_start_simu.setText(_translate("MainWindow", "开始仿真"))
        self.lab_cut_branch.setText(_translate("MainWindow", "故障处理切除支路"))
        self.label.setText(_translate("MainWindow", "仿真基本参数设置"))
        self.label_2.setText(_translate("MainWindow", "故障参数设置"))
